In [2]:
!pip list -v | grep keras

keras                                2.6.0               /home/cdr/Documents/anaconda3/lib/python3.6/site-packages pip
keras-nightly                        2.7.0.dev2021070900 /home/cdr/Documents/anaconda3/lib/python3.6/site-packages pip
You should consider upgrading via the '/home/cdr/Documents/anaconda3/bin/python3.6 -m pip install --upgrade pip' command.


In [1]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
a = np.array([[1,2,3], [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
a = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
a.ndim

3

In [ ]:
a = np.array([[1,2,3], [4,5,6]])
a.shape

(2, 3)

In [ ]:
a = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
a.shape

(1, 3, 3)

In [ ]:
a = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
a.dtype

dtype('int64')

In [7]:
a = np.arange(1,10,2)
print(a)

[1 3 5 7 9]


In [5]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
print("l'addition des deux tableaux:\n", np.add(a,b))
print("la soustraction de b de a:\n ", np.subtract(b,a))
print("la multiplication des deux tableaux:\n ", np.multiply(a,b))
print("la division de b par a:\n" ,np.divide(b,a))

l'addition des deux tableaux:
 [[ 8 10 12]
 [14 16 18]]
la soustraction de b de a:
  [[6 6 6]
 [6 6 6]]
la multiplication des deux tableaux:
  [[ 7 16 27]
 [40 55 72]]
la division de b par a:
 [[7.  4.  3. ]
 [2.5 2.2 2. ]]


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a.dot(b)

32

In [8]:
a = np.array([[1,2,3],[4,5,6]])
#exponentielle
print(np.exp(a))
#sinus
print(np.sin(a))
#cosinus
print(np.cos(a))
#tangente
print(np.tan(a))
#racine carée
print(np.sqrt(a))

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [10]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a == b

array([False, False, False])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,2,6])
print((a == b).all())

False


In [ ]:
a = np.array([1,2,3])
b = np.array([4,2,6])
print((a == b).any())

True


In [ ]:
a = np.array([1,2,3])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.median(a))
print(np.cumsum(a))

6
1
3
2.0
2.0
[1 3 6]


In [ ]:
a = np.array([[1,2,3], [4,5,6]])
a[0,2] #ligne 0 colonne 2

3

In [ ]:
a = np.array([[[1,2,3], [4,5,6], [7,8,9]]])
a[a>5]

array([6, 7, 8, 9])

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b), axis = 0)
print(c)
print(np.transpose(a))
c.reshape(3,2)

[1 2 3 4 5 6]
[1 2 3]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# Exercice 1
T1 = np.arange(0,50,2)
T2 = np.cos(T1**2)
m = np.max(T2)
np.sum(T2 == m)

1

In [ ]:
# Exercice 2
T1 = np.arange(1,7)
print(T1)
T1 = T1[::-1]
print(T1)

[1 2 3 4 5 6]
[6 5 4 3 2 1]


In [ ]:
# Exercice 3
T1 = np.random.random((3,3,3))
print("tableau:\n",T1)
y = T1[:1,:]
print("le premièr élément du tableau:\n",y)

tableau:
 [[[0.68471036 0.75327373 0.2378001 ]
  [0.25677324 0.58494458 0.29240687]
  [0.38725819 0.10486922 0.1361004 ]]

 [[0.48299209 0.09199342 0.48104331]
  [0.18331111 0.80375418 0.54499152]
  [0.07732149 0.04468401 0.87650459]]

 [[0.20384515 0.37263156 0.71778031]
  [0.35743071 0.24298263 0.31578399]
  [0.79753367 0.93289915 0.05455564]]]
le premièr élément du tableau:
 [[[0.68471036 0.75327373 0.2378001 ]
  [0.25677324 0.58494458 0.29240687]
  [0.38725819 0.10486922 0.1361004 ]]]


In [ ]:
# Exercice 4
def diagonale(T1): 
  n,p = T1.shape
  if n != p:
    return False 
    for i in range(n):
      for j in range(p): 
        if i != j and T1[i,j] != 0: 
          return False 
        return True
        T1 = np.array([[18,0,0], [0,20,0], [0,0,0]])
        diagonale(T1)

In [ ]:
#  Méthode 2 appel à la fonction diag()
def diagonale(T1): 
  n,p = T1.shape 
  if n != p: 
    return False 
  return(T1 == np.diag(np.diag(T1))).all()
  T1 = np.array([[18,0,0], [0,20,0], [0,0,0]])
  diagonale(T1)

In [ ]:
#  Exercice 5
def triangulaire_sup(T1): 
  n,p = T1.shape 
  if n != p: 
    return False 
    for i in range(n): 
      for j in range(i): 
        if T1[i,j] != 0: 
          return False 
        return True
        T1 = np.array([[18,5,6], [0,20,7], [0,0,5]])
        triangulaire_sup(T1)

In [5]:
np.diag?